# This file is auto-generated by Swagger Codegen (https://github.com/swagger-api/swagger-codegen)
# Please replace "TEST_VALUE" with a proper value and uncomment the code for testing the function
Import-Module ..\src\Sphereon.SDK.Pdf -Verbose
#using module Sphereon.SDK.Pdf

<#
Import-Module ..\src\Sphereon.SDK.Pdf -Verbose
using namespace Sphereon.SDK.Pdf.Api;
using namespace Sphereon.SDK.Pdf.Client;
using namespace Sphereon.SDK.Pdf.Model;
#>

[Sphereon.SDK.Pdf.Api.DebugHelper]::AttachDebugger()

$Script:Conversion2PDFApi= New-Object -TypeName Sphereon.SDK.Pdf.Api.Conversion2PDFApi -ArgumentList @($null)
$AccessToken = ${env:sphereon.test.accesstoken}

Write-Host "###########################"
Write-Host $AccessToken
Write-Host "###########################"
$resultSettings = New-ResultSettings -lifecycle "NONE"
Write-Host $resultSettings | ConvertTo-Json
$conversionSettings = New-ConversionSettings -engine "ADVANCED"
Write-Host $conversionSettings | ConvertTo-Json
$Script:Conversion2PDFApi.Configuration.AccessToken = $AccessToken


Describe 'Sphereon.SDK.Pdf Conversion2PDFApi' {
        Context 'Conversion2PDFApi' {

            Write-Host $Script.Conversion2PDFApi.Configuration | ConvertTo-Json
            
            
            It 'Invoke-Conversion2PDFApiCreateJob' {
                $ret = Invoke-Conversion2PDFApiCreateJob
                $ret | Should BeOfType Sphereon.SDK.Pdf.Model.ConversionJobResponse
            }
        }

        Context 'Conversion2PDFApi' {
            It 'Invoke-Conversion2PDFApiAddInputFile' {
                $ret = Invoke-Conversion2PDFApiAddInputFile -jobid "TEST_VALUE" -stream "TEST_VALUE" -fileName "TEST_VALUE"
                #$ret | Should BeOfType Sphereon.SDK.Pdf.Model.PutYourModelNameHere
                #$ret.property | Should Be 0
            }
        }

        Context 'Conversion2PDFApi' {
            It 'Invoke-Conversion2PDFApiAddInputStreamLocations' {
                $ret = Invoke-Conversion2PDFApiAddInputStreamLocations -jobid "TEST_VALUE" -inputStreamLocations "TEST_VALUE"
                #$ret | Should BeOfType Sphereon.SDK.Pdf.Model.PutYourModelNameHere
                #$ret.property | Should Be 0
            }
        }



        Context 'Conversion2PDFApi' {
            It 'Invoke-Conversion2PDFApiDeleteJob' {
                $ret = Invoke-Conversion2PDFApiDeleteJob -jobid "TEST_VALUE"
                #$ret | Should BeOfType Sphereon.SDK.Pdf.Model.PutYourModelNameHere
                #$ret.property | Should Be 0
            }
        }

        Context 'Conversion2PDFApi' {
            It 'Invoke-Conversion2PDFApiGetJob' {
                $ret = Invoke-Conversion2PDFApiGetJob -jobid "TEST_VALUE"
                #$ret | Should BeOfType Sphereon.SDK.Pdf.Model.PutYourModelNameHere
                #$ret.property | Should Be 0
            }
        }

        Context 'Conversion2PDFApi' {
            It 'Invoke-Conversion2PDFApiGetJobs' {
                $ret = Invoke-Conversion2PDFApiGetJobs -status "TEST_VALUE"
                #$ret | Should BeOfType Sphereon.SDK.Pdf.Model.PutYourModelNameHere
                #$ret.property | Should Be 0
            }
        }

        Context 'Conversion2PDFApi' {
            It 'Invoke-Conversion2PDFApiGetStream' {
                $ret = Invoke-Conversion2PDFApiGetStream -jobid "TEST_VALUE"
                #$ret | Should BeOfType Sphereon.SDK.Pdf.Model.PutYourModelNameHere
                #$ret.property | Should Be 0
            }
        }

        Context 'Conversion2PDFApi' {
            It 'Invoke-Conversion2PDFApiSubmitJob' {
                $ret = Invoke-Conversion2PDFApiSubmitJob -jobid "TEST_VALUE" -job "TEST_VALUE"
                #$ret | Should BeOfType Sphereon.SDK.Pdf.Model.PutYourModelNameHere
                #$ret.property | Should Be 0
            }
        }

}